title: News Y Data
description: >- # this means to ignore newlines until "baseurl:"
  Important information and news that are completely supported by data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://news-y-data.github.io/"
github_username:  news-y-data
relative_permalinks: false

markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache/
  - .idea/
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: assets/css/
  load_paths:
    - node_modules/

plugins:
  - jekyll-octicons

webrick:
  headers:
    Cache-Control: max-age=0



