title: News Y Data
description: >- # this means to ignore newlines until "baseurl:"
  Important information and news that are completely supported by data.
baseurl: "" # the subpath of your site, e.g. /blog

# Do not put '/' at the end for sitemap to work well
url: "https://news-y-data.github.io"
github_username:  news-y-data
relative_permalinks: false

#markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: [".jekyll-cache", ".idea", "Gemfile", "Gemfile.lock", "vendor/bundle"]

sass:
  sass_dir: assets/css/
  load_paths:
    - node_modules/

plugins:
  - jekyll-sitemap
  - jekyll-octicons

whitelist:
  - jekyll-sitemap
  - jekyll-octicons

webrick:
  headers:
    Cache-Control: max-age=0

main_image: https://news-y-data.github.io/assets/img/favicon-rect-1024x1024.png

facebook_main_image: https://news-y-data.github.io/assets/img/favicon-rect-1200x630.png

twitter_main_image: https://news-y-data.github.io/assets/img/favicon-rect-1024x1024.png
